server:
  port: 8080

springdoc:
  swagger-ui:
    layout: BaseLayout
    path: /api-docs

# Payment Gateway Specifics
bb:
  auth-base-url: ${BB_AUTH_BASE_URL:https://oauth.hm.bb.com.br}
  base-url: ${BB_PIX_BASE_URL:https://api.hm.bb.com.br}
