apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment-service
  type: ClusterIP
  ports:
    - name: user-service
      port: 8082
      targetPort: 8080
      protocol: TCP
